### ISSUE TITLE
generate 3d waypoints

### ISSUE THREAD

**Issue by MasoudSaraf** [winstxnhdw/WaypointGenerator#1]
Hi. can I generate 3D waypoints such as latitude, longitude and altitude?

**Comment by winstxnhdw** [comment]
You know what.. why not? I just pushed a change that will allow you to change the altitude of the current point by scrolling your mouse wheel up or down.  See [7621c7e](https://github.com/winstxnhdw/WaypointGenerator/commit/7621c7e0a15e2549b689383bdf8910e911432889).
